name: Updates

on:
  schedule:
    - cron: "0 12 * * *"  # Runs daily at 12:00 UTC
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Install npm-check-updates
        run: npm install -g npm-check-updates

      - name: Check for Updates
        run: ncu -u
    
      - name: Install Updated Packages
        run: npm install
      
      - name: Run Eyes Storybook
        run: npx eyes-storybook
        env: 
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}

      - name: Publish Changes to GitHub
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'master'

